// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RpcReq.proto

package com.wdq.nio.mando.codec;

public final class RpcReqProto {
  private RpcReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     ** manda消息的校验码
     * </pre>
     *
     * <code>optional int32 crcCode = 1;</code>
     */
    int getCrcCode();

    /**
     * <pre>
     ** 消息长度，包含消息头和消息体
     * </pre>
     *
     * <code>optional int32 length = 2;</code>
     */
    int getLength();

    /**
     * <pre>
     ** 会话id，集群节点内唯一，会话id生成器生成
     * </pre>
     *
     * <code>optional int64 sessionId = 3;</code>
     */
    long getSessionId();

    /**
     * <pre>
     ** 消息id
     * </pre>
     *
     * <code>optional int32 type = 4;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Header)
      HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      crcCode_ = 0;
      length_ = 0;
      sessionId_ = 0L;
      type_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              crcCode_ = input.readInt32();
              break;
            }
            case 16: {

              length_ = input.readInt32();
              break;
            }
            case 24: {

              sessionId_ = input.readInt64();
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wdq.nio.mando.codec.RpcReqProto.internal_static_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wdq.nio.mando.codec.RpcReqProto.internal_static_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wdq.nio.mando.codec.RpcReqProto.Header.class, com.wdq.nio.mando.codec.RpcReqProto.Header.Builder.class);
    }

    public static final int CRCCODE_FIELD_NUMBER = 1;
    private int crcCode_;
    /**
     * <pre>
     ** manda消息的校验码
     * </pre>
     *
     * <code>optional int32 crcCode = 1;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <pre>
     ** 消息长度，包含消息头和消息体
     * </pre>
     *
     * <code>optional int32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionId_;
    /**
     * <pre>
     ** 会话id，集群节点内唯一，会话id生成器生成
     * </pre>
     *
     * <code>optional int64 sessionId = 3;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     ** 消息id
     * </pre>
     *
     * <code>optional int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (crcCode_ != 0) {
        output.writeInt32(1, crcCode_);
      }
      if (length_ != 0) {
        output.writeInt32(2, length_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(3, sessionId_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (crcCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, crcCode_);
      }
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionId_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wdq.nio.mando.codec.RpcReqProto.Header)) {
        return super.equals(obj);
      }
      com.wdq.nio.mando.codec.RpcReqProto.Header other = (com.wdq.nio.mando.codec.RpcReqProto.Header) obj;

      boolean result = true;
      result = result && (getCrcCode()
          == other.getCrcCode());
      result = result && (getLength()
          == other.getLength());
      result = result && (getSessionId()
          == other.getSessionId());
      result = result && (getType()
          == other.getType());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
      hash = (53 * hash) + getCrcCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wdq.nio.mando.codec.RpcReqProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Header)
        com.wdq.nio.mando.codec.RpcReqProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wdq.nio.mando.codec.RpcReqProto.internal_static_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wdq.nio.mando.codec.RpcReqProto.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wdq.nio.mando.codec.RpcReqProto.Header.class, com.wdq.nio.mando.codec.RpcReqProto.Header.Builder.class);
      }

      // Construct using com.wdq.nio.mando.codec.RpcReqProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        crcCode_ = 0;

        length_ = 0;

        sessionId_ = 0L;

        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wdq.nio.mando.codec.RpcReqProto.internal_static_Header_descriptor;
      }

      public com.wdq.nio.mando.codec.RpcReqProto.Header getDefaultInstanceForType() {
        return com.wdq.nio.mando.codec.RpcReqProto.Header.getDefaultInstance();
      }

      public com.wdq.nio.mando.codec.RpcReqProto.Header build() {
        com.wdq.nio.mando.codec.RpcReqProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wdq.nio.mando.codec.RpcReqProto.Header buildPartial() {
        com.wdq.nio.mando.codec.RpcReqProto.Header result = new com.wdq.nio.mando.codec.RpcReqProto.Header(this);
        result.crcCode_ = crcCode_;
        result.length_ = length_;
        result.sessionId_ = sessionId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wdq.nio.mando.codec.RpcReqProto.Header) {
          return mergeFrom((com.wdq.nio.mando.codec.RpcReqProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wdq.nio.mando.codec.RpcReqProto.Header other) {
        if (other == com.wdq.nio.mando.codec.RpcReqProto.Header.getDefaultInstance()) return this;
        if (other.getCrcCode() != 0) {
          setCrcCode(other.getCrcCode());
        }
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wdq.nio.mando.codec.RpcReqProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wdq.nio.mando.codec.RpcReqProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int crcCode_ ;
      /**
       * <pre>
       ** manda消息的校验码
       * </pre>
       *
       * <code>optional int32 crcCode = 1;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <pre>
       ** manda消息的校验码
       * </pre>
       *
       * <code>optional int32 crcCode = 1;</code>
       */
      public Builder setCrcCode(int value) {

        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** manda消息的校验码
       * </pre>
       *
       * <code>optional int32 crcCode = 1;</code>
       */
      public Builder clearCrcCode() {

        crcCode_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <pre>
       ** 消息长度，包含消息头和消息体
       * </pre>
       *
       * <code>optional int32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       ** 消息长度，包含消息头和消息体
       * </pre>
       *
       * <code>optional int32 length = 2;</code>
       */
      public Builder setLength(int value) {

        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息长度，包含消息头和消息体
       * </pre>
       *
       * <code>optional int32 length = 2;</code>
       */
      public Builder clearLength() {

        length_ = 0;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <pre>
       ** 会话id，集群节点内唯一，会话id生成器生成
       * </pre>
       *
       * <code>optional int64 sessionId = 3;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <pre>
       ** 会话id，集群节点内唯一，会话id生成器生成
       * </pre>
       *
       * <code>optional int64 sessionId = 3;</code>
       */
      public Builder setSessionId(long value) {

        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 会话id，集群节点内唯一，会话id生成器生成
       * </pre>
       *
       * <code>optional int64 sessionId = 3;</code>
       */
      public Builder clearSessionId() {

        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       ** 消息id
       * </pre>
       *
       * <code>optional int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       ** 消息id
       * </pre>
       *
       * <code>optional int32 type = 4;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       ** 消息id
       * </pre>
       *
       * <code>optional int32 type = 4;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Header)
    }

    // @@protoc_insertion_point(class_scope:Header)
    private static final com.wdq.nio.mando.codec.RpcReqProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wdq.nio.mando.codec.RpcReqProto.Header();
    }

    public static com.wdq.nio.mando.codec.RpcReqProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    public com.wdq.nio.mando.codec.RpcReqProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string rpcReqId = 1;</code>
     */
    String getRpcReqId();
    /**
     * <code>optional string rpcReqId = 1;</code>
     */
    com.google.protobuf.ByteString
        getRpcReqIdBytes();

    /**
     * <code>optional string methodName = 2;</code>
     */
    String getMethodName();
    /**
     * <code>optional string methodName = 2;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>optional string reqTime = 3;</code>
     */
    String getReqTime();
    /**
     * <code>optional string reqTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getReqTimeBytes();
  }
  /**
   * Protobuf type {@code RpcReq}
   */
  public  static final class RpcReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RpcReq)
      RpcReqOrBuilder {
    // Use RpcReq.newBuilder() to construct.
    private RpcReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcReq() {
      rpcReqId_ = "";
      methodName_ = "";
      reqTime_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RpcReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              rpcReqId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              reqTime_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.wdq.nio.mando.codec.RpcReqProto.internal_static_RpcReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.wdq.nio.mando.codec.RpcReqProto.internal_static_RpcReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.wdq.nio.mando.codec.RpcReqProto.RpcReq.class, com.wdq.nio.mando.codec.RpcReqProto.RpcReq.Builder.class);
    }

    public static final int RPCREQID_FIELD_NUMBER = 1;
    private volatile Object rpcReqId_;
    /**
     * <code>optional string rpcReqId = 1;</code>
     */
    public String getRpcReqId() {
      Object ref = rpcReqId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rpcReqId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string rpcReqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRpcReqIdBytes() {
      Object ref = rpcReqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rpcReqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int METHODNAME_FIELD_NUMBER = 2;
    private volatile Object methodName_;
    /**
     * <code>optional string methodName = 2;</code>
     */
    public String getMethodName() {
      Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string methodName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTIME_FIELD_NUMBER = 3;
    private volatile Object reqTime_;
    /**
     * <code>optional string reqTime = 3;</code>
     */
    public String getReqTime() {
      Object ref = reqTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string reqTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReqTimeBytes() {
      Object ref = reqTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        reqTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRpcReqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rpcReqId_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, methodName_);
      }
      if (!getReqTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reqTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRpcReqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rpcReqId_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, methodName_);
      }
      if (!getReqTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reqTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.wdq.nio.mando.codec.RpcReqProto.RpcReq)) {
        return super.equals(obj);
      }
      com.wdq.nio.mando.codec.RpcReqProto.RpcReq other = (com.wdq.nio.mando.codec.RpcReqProto.RpcReq) obj;

      boolean result = true;
      result = result && getRpcReqId()
          .equals(other.getRpcReqId());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && getReqTime()
          .equals(other.getReqTime());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RPCREQID_FIELD_NUMBER;
      hash = (53 * hash) + getRpcReqId().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + REQTIME_FIELD_NUMBER;
      hash = (53 * hash) + getReqTime().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.wdq.nio.mando.codec.RpcReqProto.RpcReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcReq)
        com.wdq.nio.mando.codec.RpcReqProto.RpcReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.wdq.nio.mando.codec.RpcReqProto.internal_static_RpcReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.wdq.nio.mando.codec.RpcReqProto.internal_static_RpcReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.wdq.nio.mando.codec.RpcReqProto.RpcReq.class, com.wdq.nio.mando.codec.RpcReqProto.RpcReq.Builder.class);
      }

      // Construct using com.wdq.nio.mando.codec.RpcReqProto.RpcReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        rpcReqId_ = "";

        methodName_ = "";

        reqTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.wdq.nio.mando.codec.RpcReqProto.internal_static_RpcReq_descriptor;
      }

      public com.wdq.nio.mando.codec.RpcReqProto.RpcReq getDefaultInstanceForType() {
        return com.wdq.nio.mando.codec.RpcReqProto.RpcReq.getDefaultInstance();
      }

      public com.wdq.nio.mando.codec.RpcReqProto.RpcReq build() {
        com.wdq.nio.mando.codec.RpcReqProto.RpcReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.wdq.nio.mando.codec.RpcReqProto.RpcReq buildPartial() {
        com.wdq.nio.mando.codec.RpcReqProto.RpcReq result = new com.wdq.nio.mando.codec.RpcReqProto.RpcReq(this);
        result.rpcReqId_ = rpcReqId_;
        result.methodName_ = methodName_;
        result.reqTime_ = reqTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.wdq.nio.mando.codec.RpcReqProto.RpcReq) {
          return mergeFrom((com.wdq.nio.mando.codec.RpcReqProto.RpcReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.wdq.nio.mando.codec.RpcReqProto.RpcReq other) {
        if (other == com.wdq.nio.mando.codec.RpcReqProto.RpcReq.getDefaultInstance()) return this;
        if (!other.getRpcReqId().isEmpty()) {
          rpcReqId_ = other.rpcReqId_;
          onChanged();
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.getReqTime().isEmpty()) {
          reqTime_ = other.reqTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.wdq.nio.mando.codec.RpcReqProto.RpcReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.wdq.nio.mando.codec.RpcReqProto.RpcReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object rpcReqId_ = "";
      /**
       * <code>optional string rpcReqId = 1;</code>
       */
      public String getRpcReqId() {
        Object ref = rpcReqId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rpcReqId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string rpcReqId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRpcReqIdBytes() {
        Object ref = rpcReqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rpcReqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rpcReqId = 1;</code>
       */
      public Builder setRpcReqId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        rpcReqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string rpcReqId = 1;</code>
       */
      public Builder clearRpcReqId() {

        rpcReqId_ = getDefaultInstance().getRpcReqId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string rpcReqId = 1;</code>
       */
      public Builder setRpcReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        rpcReqId_ = value;
        onChanged();
        return this;
      }

      private Object methodName_ = "";
      /**
       * <code>optional string methodName = 2;</code>
       */
      public String getMethodName() {
        Object ref = methodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder clearMethodName() {

        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string methodName = 2;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        methodName_ = value;
        onChanged();
        return this;
      }

      private Object reqTime_ = "";
      /**
       * <code>optional string reqTime = 3;</code>
       */
      public String getReqTime() {
        Object ref = reqTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reqTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string reqTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReqTimeBytes() {
        Object ref = reqTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          reqTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string reqTime = 3;</code>
       */
      public Builder setReqTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        reqTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqTime = 3;</code>
       */
      public Builder clearReqTime() {

        reqTime_ = getDefaultInstance().getReqTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string reqTime = 3;</code>
       */
      public Builder setReqTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        reqTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:RpcReq)
    }

    // @@protoc_insertion_point(class_scope:RpcReq)
    private static final com.wdq.nio.mando.codec.RpcReqProto.RpcReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.wdq.nio.mando.codec.RpcReqProto.RpcReq();
    }

    public static com.wdq.nio.mando.codec.RpcReqProto.RpcReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcReq>
        PARSER = new com.google.protobuf.AbstractParser<RpcReq>() {
      public RpcReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RpcReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcReq> getParserForType() {
      return PARSER;
    }

    public com.wdq.nio.mando.codec.RpcReqProto.RpcReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcReq_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RpcReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014RpcReq.proto\"J\n\006Header\022\017\n\007crcCode\030\001 \001(" +
      "\005\022\016\n\006length\030\002 \001(\005\022\021\n\tsessionId\030\003 \001(\003\022\014\n\004" +
      "type\030\004 \001(\005\"?\n\006RpcReq\022\020\n\010rpcReqId\030\001 \001(\t\022\022" +
      "\n\nmethodName\030\002 \001(\t\022\017\n\007reqTime\030\003 \001(\tB&\n\027c" +
      "om.wdq.nio.mando.codecB\013RpcReqProtob\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_descriptor,
        new String[] { "CrcCode", "Length", "SessionId", "Type", });
    internal_static_RpcReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RpcReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RpcReq_descriptor,
        new String[] { "RpcReqId", "MethodName", "ReqTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
